language: php
php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7'
before_script:
    - wget https://phar.phpunit.de/phpunit-3.7.phar
script: cd test-cases && php ../phpunit-3.7.phar --bootstrap bootstrap.php
