language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - 7.1
    - 7.2

matrix:
    allow_failures:
        php: 7.1
        php: 7.2

# install packages explicitly
install:
  - composer self-update && composer install

# show me what phpunit version we are running
before_script:
  - vendor/bin/phpunit --version

# run the test suite
script: cd test-cases && php ../vendor/bin/phpunit --bootstrap bootstrap.php
