language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - 7.1
    - 7.2

matrix:
    allow_failures:
        php: 7.1
        php: 7.2

script: cd test-cases && phpunit --bootstrap bootstrap.php
