<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-12 at 13:17:14.
 */
class AmazonReportTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AmazonReport
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->resetLog();
        $this->object = new AmazonReport('BigKitchen', null, true);
        $this->object->setConfig('/var/www/athena/plugins/newAmazon/test-cases/test-config.php');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testSetUp(){
        $obj = new AmazonReport('BigKitchen', '77', true);
        
        $o = $obj->getOptions();
        $this->assertArrayHasKey('ReportId',$o);
        $this->assertEquals('77', $o['ReportId']);
    }
    
    public function testSetReportId(){
        $this->assertNull($this->object->setReportId(777));
        $o = $this->object->getOptions();
        $this->assertArrayHasKey('ReportId',$o);
        $this->assertEquals(777,$o['ReportId']);
        $this->assertNull($this->object->setReportId('777')); //works for number strings
        $this->assertFalse($this->object->setReportId('five')); //but not other strings
        $this->assertFalse($this->object->setReportId(null)); //won't work for other things
    }
    
    public function testFetchReport(){
        $this->resetLog();
        $this->object->setMock(true,'fetchReport.xml');
        
        $this->assertFalse($this->object->fetchReport()); //no report ID set yet
        
        $this->object->setReportId('777');
        $ok = $this->object->fetchReport(); //now it is good
        $this->assertNull($ok);
        
        $o = $this->object->getOptions();
        $this->assertEquals('GetReport',$o['Action']);
        
        $check = $this->parseLog();
        $this->assertEquals('Single Mock File set: fetchReport.xml',$check[1]);
        $this->assertEquals('Report ID must be set in order to fetch it!',$check[2]);
        $this->assertEquals('Fetched Mock File: mock/fetchReport.xml',$check[3]);
        
        return $this->object;
        
    }
    
    /**
     * @depends testFetchReport
     */
    public function testSaveReport($o){
        $path = '/var/www/athena/plugins/newAmazon/test-cases/mock/saveReport.xml';
        $path2 = '/var/www/athena/plugins/newAmazon/test-cases/mock/fetchReport.xml';
        $o->saveReport($path);
        $check = $this->parseLog();
        $this->assertEquals("Successfully saved report #777 at $path",$check[1]);
        $this->assertFileEquals($path2, $path);
        $this->assertFalse($this->object->saveReport('here')); //not fetched yet for this object
    }
    
//    /**
//     * @depends testFetchTrackingDetails
//     */
//    public function testGetDetails($o){
//        $get = $o->getDetails();
//        $this->assertInternalType('array',$get);
//        
//        $x = array();
//        $x['PackageNumber'] = '42343';
//        $x['TrackingNumber'] = '3A18351E0390447173';
//        $x['CarrierCode'] = 'UPS';
//        $x['CarrierPhoneNumber'] = '206-000-0000';
//        $x['CarrierURL'] = 'http://www.ups.com/';
//        $x['ShipDate'] = '2012-03-09T10:27:10Z';
//        $x['ShipToAddress']['City'] = 'Seattle';
//        $x['ShipToAddress']['State'] = 'WA';
//        $x['ShipToAddress']['Country'] = 'US';
//        $x['CurrentStatus'] = 'DELIVERED';
//        $x['SignedForBy'] = 'John';
//        $x['EstimatedArrivalDate'] = '2012-03-09T10:00:00Z';
//        $x['TrackingEvents'][0]['EventDate'] = '2012-03-09T08:48:53Z';
//        $x['TrackingEvents'][0]['EventAddress']['City'] = 'Reno';
//        $x['TrackingEvents'][0]['EventAddress']['State'] = 'NV';
//        $x['TrackingEvents'][0]['EventAddress']['Country'] = 'US';
//        $x['TrackingEvents'][0]['EventCode'] = 'EVENT_202';
//        $x['TrackingEvents'][1]['EventDate'] = '2012-03-10T10:27:10Z';
//        $x['TrackingEvents'][1]['EventAddress']['City'] = 'Seattle';
//        $x['TrackingEvents'][1]['EventAddress']['State'] = 'WA';
//        $x['TrackingEvents'][1]['EventAddress']['Country'] = 'US';
//        $x['TrackingEvents'][1]['EventCode'] = 'EVENT_301';
//        $x['AdditionalLocationInfo'] = 'FRONT_DESK';
//        
//        $this->assertEquals($x,$get);
//        
//        $this->assertFalse($this->object->getDetails()); //not fetched yet for this object
//    }
    
    /**
     * Resets log for next test
     */
    protected function resetLog(){
        file_put_contents('log.txt','');
    }
    
    /**
     * gets the log contents
     */
    protected function getLog(){
        return file_get_contents('log.txt');
    }
    
    /**
     * gets log and returns messages in an array
     * @param string $s pre-fetched log contents
     * @return array list of message strings
     */
    protected function parseLog($s = null){
        if (!$s){
            $s = $this->getLog();
        }
        $temp = explode("\n",$s);
        
        $return = array();
        foreach($temp as $x){
            $tempo = explode('] ',$x);
            $return[] = trim($tempo[1]);
        }
        array_pop($return);
        return $return;
    }

}
