<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-12 at 13:17:14.
 */
class AmazonFeedResultTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AmazonFeedResult
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->resetLog();
        $this->object = new AmazonFeedResult('BigKitchen', null, true);
        $this->object->setConfig('/var/www/athena/plugins/newAmazon/test-cases/test-config.php');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testSetUp(){
        $obj = new AmazonFeedResult('BigKitchen', 77, true);
        
        $o = $obj->getOptions();
        $this->assertArrayHasKey('FeedSubmissionId',$o);
        $this->assertEquals(77, $o['FeedSubmissionId']);
    }
    
    public function testSetFeedId(){
        $ok = $this->object->setFeedId(77);
        $this->assertNull($ok);
        $o = $this->object->getOptions();
        $this->assertArrayHasKey('FeedSubmissionId',$o);
        $this->assertEquals(77, $o['FeedSubmissionId']);
        $this->assertFalse($this->object->setFeedId('string'));
    }
    
    public function testFetchFeedResult(){
        $this->resetLog();
        $this->object->setMock(true,'fetchFeedResult.xml');
        $this->assertFalse($this->object->fetchFeedResult()); //no ID set yet
        $this->object->setFeedId(77);
        $ok = $this->object->fetchFeedResult();
        $this->assertNull($ok);
        
        $check = $this->parseLog();
        $this->assertEquals('Single Mock File set: fetchFeedResult.xml',$check[1]);
        $this->assertEquals('Feed Submission ID must be set in order to fetch it!',$check[2]);
        $this->assertEquals('Fetched Mock File: mock/fetchFeedResult.xml',$check[3]);
        
        return $this->object;
    }
    
    /**
     * @depends testFetchFeedResult
     */
    public function testSaveFeed($o){
        $this->resetLog();
        $this->assertFalse($this->object->saveFeed('mock/saveFeed.xml')); //nothing yet
        $o->saveFeed('/var/www/athena/plugins/newAmazon/test-cases/mock/saveFeed.xml');
        $check = $this->parseLog();
        $this->assertEquals('Successfully saved feed #77 at /var/www/athena/plugins/newAmazon/test-cases/mock/saveFeed.xml',$check[0]);
    }
    
    /**
     * Resets log for next test
     */
    protected function resetLog(){
        file_put_contents('log.txt','');
    }
    
    /**
     * gets the log contents
     */
    protected function getLog(){
        return file_get_contents('log.txt');
    }
    
    /**
     * gets log and returns messages in an array
     * @param string $s pre-fetched log contents
     * @return array list of message strings
     */
    protected function parseLog($s = null){
        if (!$s){
            $s = $this->getLog();
        }
        $temp = explode("\n",$s);
        
        $return = array();
        foreach($temp as $x){
            $tempo = explode('] ',$x);
            $return[] = trim($tempo[1]);
        }
        array_pop($return);
        return $return;
    }

}
